name: Compile

on: [push, pull_request, workflow_dispatch]

jobs:
  artifacts-mingw-w64:
    runs-on: windows-latest # ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install MinGW
      run: choco install mingw
      
    #- name: Install MinGW
    #  uses: egor-tensin/setup-mingw@v2

    - name: Install MinGW
      run: gcc EDRSilencer.c utils.c -o EDRSilencer.exe -lfwpuclnt
      # run: x86_64-w64-mingw32-gcc EDRSilencer.c utils.c -o EDRSilencer.exe -lfwpuclnt
